### ISSUE TITLE
imageID and instanceType should be common for all the masters and workers

### ISSUE THREAD

**Issue by fgimenez** [giantswarm/awstpr#47]
Currently we have:
```
masters:
    - imageid: "{{.Values.aws.ami}}"
      instancetype: "{{.Values.aws.instanceTypeMaster}}"

workers:
    - imageid: "{{.Values.aws.ami}}"
      instancetype: "{{.Values.aws.instanceTypeWorker}}"
    - imageid: "{{.Values.aws.ami}}"
      instancetype: "{{.Values.aws.instanceTypeWorker}}"
```
image ID and instanceType should not be defined at the array item level, but at the master/worker level.

**Comment by kopiczko** [comment]
I think instance types should be common for the masters. But I wouldn't be so sure about the workers.

**Comment by puja108** [comment]
+1 We should support different worker types in a cluster at some point. Masters inside 1 cluster should be same.

**Comment by xh3b4sd** [comment]
@kopiczko @rossf7 we discussed in the SIG operator sync. Please drop your opinions here and maybe even sort the labels. <3

**Comment by kopiczko** [comment]
We decided this isn't a boyscouting issue. This is bigger story and needs spec.

Currently our custom objects look like this:

```
spec:
  cluster:
    masters:
    - hostname: "master-1"
    workers:
    - hostname: "worker-1"
  azure:
    masters:
    - vmSize: "Standard_A1"
      dataDiskSizeGB: 50
      adminUsername: "core"
      adminSSHKeyData: "ssh-rsa AAAAB3NzaC1y user@location"
      osImage:
        publisher: "CoreOs"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0"
    workers:
    - vmSize: "Standard_A1"
      dataDiskSizeGB: 50
      adminUsername: "core"
      adminSSHKeyData: "ssh-rsa AAAAB3NzaC1y user@location"
      osImage:
        publisher: "CoreOs"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0" 
    - vmSize: "Standard_A1"
      dataDiskSizeGB: 50
      adminUsername: "core"
      adminSSHKeyData: "ssh-rsa AAAAB3NzaC1y user@location"
      osImage:
        publisher: "CoreOs"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0" 
    - vmSize: "Standard_A1"
      dataDiskSizeGB: 200
      adminUsername: "core"
      adminSSHKeyData: "ssh-rsa AAAAB3NzaC1y user@location"
      osImage:
        publisher: "CoreOs"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0" 
```

There is a lot of repetition and also length of `cluster.masters` has to be equal to length of `azure.master`. This is cumbersome.

Second problem is that we need node IDs but (1) we don't have reliable way of assigning them to machines (e.g. when using ASG) and (2) nodes happen to be recreated, so assigning the same IDs to them can be misleading.

- - -

My proposition is to remove `spec.cluster.masters` and `spec.cluster.workers` keys, and replace `spec.PROVIDER.masters` and `spec.PROVIDER.workers` with something similar to kops instance groups: https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md

Then the operator should also maintain new keys: `status.nodes.masters` and `status.nodes.workers` where it would fill information about current nodes in the cluster. That information could be used to display cluster state in our dashboards and other UI tools.

Example:

```
spec:
  azure:
    nodes:
      adminUsername: "core"
      adminSSHKeyData: "ssh-rsa AAAAB3NzaC1y user@location"
      osImage:
        publisher: "CoreOs"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0" 
      masters:
      - count: 1
        vmSize: "Standard_A1"
        dataDiskSizeGB: 50
      workers:
      - count: 2 
        vmSize: "Standard_A1"
        dataDiskSizeGB: 50
      - count: 1 
        vmSize: "Standard_A1"
        dataDiskSizeGB: 200
status:
  nodes:
    masters:
    - id: "master-1"
      size: "Standard_A1"
      dataDiskSizeGB: 50
      os: "CoreOS 1465.7.0" 
    workers:
    - id: "worker-1"
      size: "Standard_A1"
      dataDiskSizeGB: 50
      os: "CoreOS 1465.7.0" 
    - id: "worker-2"
      size: "Standard_A1"
      dataDiskSizeGB: 50
      os: "CoreOS 1465.7.0" 
    - id: "worker-3"
      size: "Standard_A1"
      dataDiskSizeGB: 200
      os: "CoreOS 1465.7.0" 
```

Important part is `spec.PROVIDER.nodes.masters` can differ between operators, but `status.nodes.masters` has to be aligned so it can be digested by kubernetesd/cluster-service.d
